---
apiVersion: v1
kind: Service
metadata:
  name: clodevo-proxy
spec:
  type: NodePort
  selector:
    app: clodevo-proxy
  ports:
  - name: proxy
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: clodevo-admin
spec:
  type: ClusterIP
  selector:
    app: clodevo-proxy
  ports:
  - name: admin
    port: 9090
    targetPort: 9090
    protocol: TCP
